version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findtax-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "5000:3000"
    networks:
      - app-network
    volumes:
      - ./:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    container_name: findtax-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./findtax-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 