version: '3.8'

services:
  api:
    image: node:18-alpine
    container_name: findtax-api-simple
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_VERSION=/api/v1
      - POSTGRES_HOST=ep-empty-cloud-a5twjwlc-pooler.us-east-2.aws.neon.tech
      - POSTGRES_PORT=5432
      - POSTGRES_USER=neondb_owner
      - POSTGRES_PASSWORD=TSXrIH4tRzi8
      - POSTGRES_DB=findtaxdb
      - POSTGRES_SCHEMA=public
      - POSTGRES_SSL=true
    ports:
      - "5001:3000"
    volumes:
      - ./:/app 