version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findtax-api-standalone
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_VERSION=/api/v1
      - POSTGRES_HOST=ep-gentle-darkness-a54jwqe9-pooler.us-east-2.aws.neon.tech
      - POSTGRES_PORT=5432
      - POSTGRES_USER=neondb_owner
      - POSTGRES_PASSWORD=npg_iFXJxdr1s4Ml
      - POSTGRES_DB=findtaxdb
      - POSTGRES_SCHEMA=public
      - POSTGRES_SSL=true
    ports:
      - "5001:3000"
    volumes:
      - ./:/app
      - /app/node_modules 